apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: coroot
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'dual-app'
        static_configs:
          - targets: ['10.42.0.115:5005']

