apiVersion: v1
kind: Service
metadata:
  name: coroot-dualtrace
  namespace: coroot
spec:
  type: NodePort
  selector:
    app: coroot-dualtrace
  ports:
    - name: http
      port: 5004
      targetPort: 5004
      nodePort: 32080
    - name: metrics
      port: 8001
      targetPort: 8001
      nodePort: 32081

