apiVersion: v1
kind: Service
metadata:
  name: coroot-demo
  namespace: coroot
spec:
  type: NodePort
  selector:
    app: coroot-demo
  ports:
    - name: http
      port: 5003
      targetPort: 5003
      nodePort: 31080
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 31081

