apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: coroot
spec:
  type: NodePort
  selector:
    app: otel-collector
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
      nodePort: 30417
    - name: http
      port: 4318
      targetPort: 4318
      nodePort: 30418
    - name: metrics
      port: 8889
      targetPort: 8889
      nodePort: 30489

