apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: coroot
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      otlphttp/coroot:
        endpoint: "http://135.13.28.200:32598"
        encoding: proto
        headers:
          "x-api-key": "LnSnWdU392S3uTdQZWXLJDrOMLFYqhbr"
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/coroot]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/coroot]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]

