apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - port: 4317
      name: grpc
    - port: 4318
      name: http
  type: ClusterIP

