apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp1
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30036   # You can access it on http://<NodeIP>:30036

