apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector2
  namespace: coroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector2
  template:
    metadata:
      labels:
        app: otel-collector2
    spec:
      containers:
        - name: otel-collector2
          image: otel-collector-custom:latest
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 4318  # OTLP HTTP
            - containerPort: 8889  # Prometheus metrics exporter
          volumeMounts:
            - name: config-vol
              mountPath: /etc/otelcol
      volumes:
        - name: config-vol
          configMap:
            name: otel-collector-config

