apiVersion: v1
kind: Service
metadata:
  name: coroot-dualtrace-new
  namespace: coroot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5005"
    prometheus.io/path: "/metrics"  
spec:
  type: NodePort
  selector:
    app: coroot-dualtrace-new
  ports:
    - name: http
      port: 5005
      targetPort: 5005
      nodePort: 31085
    - name: metrics
      port: 8002
      targetPort: 8002
      nodePort: 31086

